uploads = []
generated = []

[[outputs]]
id = "2X3RrwD-R0LQE7EHa4HCB"
uri = "file://wordpress-demo-import.xml"
type = "unspecified"
title = "WordPress Demo Import - 20 Artículos"
logical_id = "824d8294-50f9-4cd9-9637-fb78b705afd3"
